---
#-------------------------------
# General Site Settings
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site, e.g. http://example.com

title: Pretty Little Things | By Avnika Bhandari
logo: /assets/images/logo.png # You can add own logo
description:  Pretty Little Things, a place where creativity, art, and imagination meet.
copyright: Please DM [Avnikkaa](http://instagram.com/prettylittlethings.24) for using any image/content
# Preloader
preloader: true # To disable preloader change value to false

menu:
  - name: Home
    url: /
  - name: About
    url: /about/
  - name: Contact
    url: /contact/

# *** NOTE ***
# You can add submenus. For example:

#  menu:
#  - name: Home
#    url: /
#    submenu:
#     - name: Peru
#       url: /peru/
# ----------------------------------

layout_home_page: true # Homepage layout ( two layout is available, you can set the another layout by change the value of layout_home_page "true" to "false")

featured-post-slider: true # You can enable or disable the featured-post-slider using true or false values.

#-------------------------------
# Hero Section
hero:
  hero-subtitle: Pretty Little Things offers handmade soaps, scented candles, and unique resin products crafted with love by Avnika Bhandari. Each piece is one-of-a-kind, exclusively made by hand to provide you with an enjoyable and sensory experience. 
  hero-banner: /assets/images/banner-img.png # Add your banner image '/assets/images/'

#-------------------------------
# Author Settings
author:
  name: Avnikkaa & Karan Bhandari

#-------------------------------
# Contact Info
contact:
  email: avnika18@live.com
  phone: 
  address:
    city: Bangalore
    street: Sraddha Whitecliff, Seegehalli Village Rd, kadugodi

# Contact Form
contact-form: avnika18@live.com

# Social links
social:
  - { icon: "ti-instagram", link: "https://instagram.com/prettylittlethings.24" }
  - { icon: "ti-shopping-cart", link: "https://prettylittlethingsab.etsy.com" }
  - { icon: "ti-bag", link: "https://bit.ly/flipkartplt156" }
  - { icon: "ti-desktop", link: "https://tinyurl.com/plt156" }

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
userID: 4044026246
accessToken: 4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-archives

paginate: 10
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

# categories
jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: "/category/:name/"

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
